name: .config
description: Blogging about IT
meta_description: "Its a space to learn real IT"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://yourblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Gileno Duarte"

# Disqus config
disqus-shortname: ""
